### PR TITLE
Drop support for Python2 and make Python 3.8 the min required version.

### PR DESCRIPTION
**Pull request by mikedarcy**
Remove conditional code for PY2 support.
Bump version to 1.7.0 (minor version update).

### CODE REVIEW

**Comment by robes** [comment]
It looks good to me. Did you run the tests?

**Review by robes — APPROVED** [review]
Changes look good to me. Did you run the tests?

**Comment by mikedarcy** [comment]
> Changes look good to me. Did you run the tests?

I did not. I'll give it a try tomorrow.

**Comment by mikedarcy** [comment]
> > Changes look good to me. Did you run the tests?
> 
> I did not. I'll give it a try tomorrow.

Tests passed.

**Pull request merged**
